[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pythontomaestro"
version = "0.1.0"
authors = [
  { name="Dhiraj", email="dhirajdas.666@gmail.com" },
]
description = "A tool to convert Python automation scripts (Selenium/Appium) to Maestro YAML flows."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pyyaml",
]

[project.optional-dependencies]
dev = ["pytest>=7"]

[project.scripts]
pythontomaestro = "src.cli:main"

[project.urls]
"Homepage" = "https://github.com/godhiraj-code/pythontomaestro"
"Bug Tracker" = "https://github.com/godhiraj-code/pythontomaestro/issues"

[tool.setuptools]
packages = ["src"]

[tool.pytest.ini_options]
python_files = ["test_*.py"]
